### ISSUE TITLE
Desarrollar módulo de registro de afiliaciones (registro 40)

### ISSUE THREAD

**Issue by ivancas84** [ivancas84/magistrados-estructura#5]
* [x] Desarrollar vista persona-admin
* [x] Desarrollar vista persona-fieldset: [magistrados-angular](https://github.com/ivancas84/magistrados-angular/issues/7)
* [x] Desarrollar controlador de persistencia de persona: [magistrados-estructura](https://github.com/ivancas84/magistrados-estructura/pull/9) - [php-core](https://github.com/ivancas84/php-core/pull/17) - [php-structure-gen](https://github.com/ivancas84/php-structure-gen/pull/3)
* [x] Desarrollar subcomponente "search-go" para buscar persona: [angular-core-md](https://github.com/ivancas84/angular-core-md/issues/13)
* [x] Refinamiento del módulo de persona
___
* [x] Desarrollar vista afiliacion-table (visualización de estados del registro 40): [magistrados-angular](https://github.com/ivancas84/magistrados-angular/issues/9)
* [x] Desarrollar vista afiliacion-admin
* [x] Desarrollar vista afiliacion-fieldset
* [x] Desarrollar controlador de persistencia de afiliacion

**Comment by ivancas84** [comment]
### Tareas adicionales
* Procesamiento de fechas en formato JSON
* Configurar clases estructurales
* Modificar controlador "All": Definir json mediante clase Values

**Comment by ivancas84** [comment]
Tareas de refinamiento
* [x] Definir valores por defecto: [magistrados-angular](https://github.com/ivancas84/magistrados-angular/pull/15) - [php-core](https://github.com/ivancas84/php-core/pull/24) - [php-structure-gen](https://github.com/ivancas84/php-structure-gen/pull/8) - [angular-gen-md](https://github.com/ivancas84/angular-gen-md/pull/16)
* [x] Nuevo ruteo de persistencia: [angular-core-md](https://github.com/ivancas84/angular-core-md/pull/22), [magistrados-angular](https://github.com/ivancas84/magistrados-angular/pull/16)
